[theme]
primaryColor = "#FF6600"
backgroundColor = "#121212"
secondaryBackgroundColor = "#222222"
textColor = "#FFFFFF"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 50
maxMessageSize = 50
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
fastReruns = true 