[theme]
primaryColor = "#3498db"  # Beem blue
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#343a40"
font = "sans serif"

[server]
runOnSave = true
maxUploadSize = 50
maxMessageSize = 50
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
fastReruns = true 